version: 2.1

executors:
  ruby_with_postgres:
    docker:
      - image: cimg/ruby:2.7.7-node
      - image: 'circleci/postgres:13-buster-ram'
        environment:
          - POSTGRES_USER: foobar
          - POSTGRES_PASSWORD: hogehoge

commands:
  check-psql:
    steps:
      - run: psql --version
      - run: dockerize -wait tcp://127.0.0.1:5432
      - run: PGPASSWORD=hogehoge psql -h 127.0.0.1 -p 5432 -U foobar -d postgres -c "SELECT 1;"

jobs:
  postgres13:
    resource_class: small
    executor: ruby_with_postgres
    steps:
      - checkout
      # cimg/ruby:2.7.7-node does come with psql already installed @ v12
      - check-psql
      - run:
          name: Install psql 13 explicitly
          command: |
            # Ref: https://computingforgeeks.com/how-to-install-postgresql-13-on-ubuntu/
            sudo apt -y update && sudo apt -y upgrade
            curl -fsSL https://www.postgresql.org/media/keys/ACCC4CF8.asc|sudo gpg --dearmor -o /etc/apt/trusted.gpg.d/postgresql.gpg
            echo "deb http://apt.postgresql.org/pub/repos/apt/ `lsb_release -cs`-pgdg main" |sudo tee  /etc/apt/sources.list.d/pgdg.list
            sudo apt install -y postgresql-client-13
      - check-psql
      
workflows:
  main:
    jobs:
      - postgres13
