version: 2.1

executors:
  ruby_with_postgres:
    docker:
      - image: cimg/ruby:2.7.7-node
        <<: *ruby_envs
      - image: 'circleci/postgres:13-buster-ram'
        environment:
          - POSTGRES_USER: foobar
          - POSTGRES_PASSWORD: hogehoge

jobs:
  postgres13:
    resource_class: small
    executor: ruby_with_postgres
    steps:
      - checkout
      - run:
          name: Install psql
          command: |
            sudo apt-get update
            sudo apt-get install -y postgresql-client-13

workflows:
  main:
    jobs:
      - postgres13
