version: 2.1

jobs:
  pull:
    parameters:
      img:
        type: string
    docker:
      - image: cimg/base:current
    resource_class: medium
    steps:
      - checkout
      - setup_remote_docker
      - run: docker pull << parameters.img >>

workflows:
  main:
    jobs:
      - pull:
          matrix:
            parameters:
              img:
                - "ubuntu:20.04"
                - "ubuntu:18.04"
